force-app/main/default/objects/Case/fields/Store__c.field-meta.xml
<CustomField>
    <fullName>Store__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Store</label>
    <referenceTo>Store__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Store__c/Store__c.object-meta.xml
<CustomObject>
    <description>Represents a Wired Brain Coffee Retail Store</description>
    <label>Store</label>
    <nameField>
        <label>Store Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stores</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Store__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <description>City the store is located in</description>
    <label>City</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Store__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <description>Country the store is located in</description>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Brazil</fullName>
            </value>
            <value>
                <fullName>Canada</fullName>
            </value>
            <value>
                <fullName>France</fullName>
            </value>
            <value>
                <fullName>India</fullName>
            </value>
            <value>
                <fullName>Mexico</fullName>
            </value>
            <value>
                <fullName>United Kingdom</fullName>
            </value>
            <value>
                <fullName>United States</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Store__c/fields/Customer_Satisfaction_Score__c.field-meta.xml
<CustomField>
    <fullName>Customer_Satisfaction_Score__c</fullName>
    <label>Customer Satisfaction Score</label>
    <precision>17</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Store__c/fields/Date_of_Establishment__c.field-meta.xml
<CustomField>
    <fullName>Date_of_Establishment__c</fullName>
    <label>Date of Establishment</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Store__c/fields/Latest_Health_Score__c.field-meta.xml
<CustomField>
    <fullName>Latest_Health_Score__c</fullName>
    <label>Latest Health Score</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Store__c/fields/State_Province__c.field-meta.xml
<CustomField>
    <fullName>State_Province__c</fullName>
    <label>State/Province</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Store__c/fields/Street__c.field-meta.xml
<CustomField>
    <fullName>Street__c</fullName>
    <description>The street where the store is located</description>
    <label>Street</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Store__c/fields/Zip_Postal_Code__c.field-meta.xml
<CustomField>
    <fullName>Zip_Postal_Code__c</fullName>
    <label>Zip/Postal Code</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/StoreTests.cls
@isTest
public with sharing class StoreTests {
    @testSetup
    static void createRecords(){
       Store__c store = new Store__c();
       store.Name = 'San Francisco Hub';
       store.Latest_Health_Score__c = 100;
       store.Customer_Satisfaction_Score__c = 90.00;
       store.Date_of_Establishment__c = Date.today().addYears(-1);
       store.Street__c = '123 Sesame St.';
       store.City__c = 'San Francisco';
       store.State_Province__c = 'CA';
       store.Zip_Postal_Code__c = '95102';
       store.Country__c = 'United States';
       insert store;
    }

    @isTest
    // Test to confirm that StoreTrigger and Handler work correctly
    static void testCustomerSatisfactionChange() {
        // Get the initial store and any existing cases
        List<Store__c> stores = [SELECT Id, Customer_Satisfaction_Score__c
                                 FROM Store__c
                                 WHERE Name = 'San Francisco Hub'];
        Integer caseCountBefore = [SELECT COUNT()
                                   FROM Case
                                   WHERE Store__c = :stores[0].Id];

        // Run the code
        Test.startTest();
        stores[0].Customer_Satisfaction_Score__c = 70;
        update stores;
        Test.stopTest();

        // Get any cases created after the code ran and confirm details
        List<Case> casesAfter = [SELECT Subject, Status, Priority, Store__c
                                FROM Case WHERE Store__c = :stores[0].Id];

        System.assertEquals(caseCountBefore + 1, casesAfter.size(), 'One new case should have been created');
        System.assertEquals('Poor Customer Satisfaction', casesAfter[0].Subject,
                            'Subject should be Poor Customer Satisfaction');
        System.assertEquals('New', casesAfter[0].Status, 'Status should be New');
        System.assertEquals('High', casesAfter[0].Priority, 'Priority should be High');
        System.assertEquals(false, StoreTriggerHandler.platformEventsFailed, 'All platform events should succeed');
    }

    @isTest
    // Test to confirm StoreControllerExt works correctly
    static void testStoreControllerExt() {
       // Get the initial store and any existing cases
        List<Store__c> stores = [SELECT Id, Customer_Satisfaction_Score__c
                                 FROM Store__c
                                 WHERE Name = 'San Francisco Hub'];
        Integer caseCountBefore = [SELECT COUNT()
                                   FROM Case
                                   WHERE Store__c = :stores[0].Id];
        
        // Initialize the controller extension
        ApexPages.StandardController stdCtrlr = new ApexPages.StandardController(stores[0]);
	    StoreControllerExt extension  = new StoreControllerExt(stdCtrlr);

        // Run the code
        Test.startTest();
        stores[0].Customer_Satisfaction_Score__c = 70;
        update stores;

        List<Case> openCases = extension.getOpenCases();
        Test.stopTest();                         
		
        System.assertEquals(caseCountBefore + 1, openCases.size(), 'One new case should have been created');
        System.assertEquals('Poor Customer Satisfaction', openCases[0].Subject,
                            'Subject should be Poor Customer Satisfaction');
        System.assertEquals('New', openCases[0].Status, 'Status should be New');
        System.assertEquals('High', openCases[0].Priority, 'Priority should be High');
    }
}