force-app/main/default/objects/Store__c/Store__c.object-meta.xml
<CustomObject>
    <description>Represents a Wired Brain Coffee Retail Store</description>
    <label>Store</label>
    <nameField>
        <label>Store Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stores</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Store__c/fields/Buzz_Id__c.field-meta.xml
<CustomField>
    <fullName>Buzz_Id__c</fullName>
    <description>External Id from Wired Brain Coffee&apos;s external system Buzz</description>
    <externalId>true</externalId>
    <label>Buzz Id</label>
    <length>100</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Store__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <description>City the store is located in</description>
    <label>City</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Store__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <description>Country the store is located in</description>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Brazil</fullName>
            </value>
            <value>
                <fullName>Canada</fullName>
            </value>
            <value>
                <fullName>France</fullName>
            </value>
            <value>
                <fullName>India</fullName>
            </value>
            <value>
                <fullName>Mexico</fullName>
            </value>
            <value>
                <fullName>United Kingdom</fullName>
            </value>
            <value>
                <fullName>United States</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Store__c/fields/State_Province__c.field-meta.xml
<CustomField>
    <fullName>State_Province__c</fullName>
    <label>State/Province</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/StoreCustomController.cls
/**
 * @author - Adam Olshansky
 * @description - Custom Controller to be used for a Visualforce page on Store records
 */
public without sharing class StoreCustomController {
    public final Store__c currentStore {get; set;}
    public String name {get; set;}
    public String buzzId {get; set;}
    public String city {get; set;}
    public String stateProvince {get; set;}
    public String country {get; set;}

    /**
     * @description - Constructor for Visualforce controller.
     * Specifies the store record being used by the page based on the id parameter
     */
    public StoreCustomController() {
        Id idFromUrl = ApexPages.currentPage().getParameters().get('id');
        if(idFromUrl != null) {
            this.currentStore = [SELECT Id, Name, Buzz_Id__c, City__c, State_Province__c, Country__c
                                FROM Store__c
                                WHERE Id = :ApexPages.currentPage().getParameters().get('id')];
            this.name = this.currentStore.Name;
            this.buzzId = this.currentStore.Buzz_Id__c;
            this.city = this.currentStore.City__c;
            this.stateProvince = this.currentStore.State_Province__c;
            this.country = this.currentStore.Country__c;
        } else {
            this.currentStore = new Store__c();
        }
    }

    /**
     * @description - Custom save action to check a user's access before saving
     * @return - A reference to the Store record detail page to be redirected to
     */
    public PageReference save() {
        // Check if the user has access to create and update stores
        if(Schema.sObjectType.Store__c.isCreateable() &&
            Schema.sObjectType.Store__c.isUpdateable()) {
            this.currentStore.Name = this.name;
            this.currentStore.Buzz_Id__c = this.buzzId;
            this.currentStore.City__c = this.city;
            this.currentStore.State_Province__c = this.stateProvince;
            this.currentStore.Country__c = this.country;
            upsert this.currentStore;
            return new PageReference('/' + this.currentStore.Id);
        }
        // Send an error message to the page
        ApexPages.Message failureMessage = new ApexPages.Message(ApexPages.Severity.ERROR,
                                            'User does not have access to create or edit a store');
        ApexPages.addMessage(failureMessage);
        return null;
    }

    /**
     * @description - Custom cancel action
     * @return - A reference to the Store tab to be redirected to
     */
    public PageReference cancel() {
        return new PageReference('/lightning/o/Store__c/home');
    }
}