force-app/main/default/objects/Store__c/Store__c.object-meta.xml
<CustomObject>
    <description>Represents a Wired Brain Coffee Retail Store</description>
    <label>Store</label>
    <nameField>
        <label>Store Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stores</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Store__c/fields/Latest_Health_Score__c.field-meta.xml
<CustomField>
    <fullName>Latest_Health_Score__c</fullName>
    <label>Latest Health Score</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Store_Supply_Order__c/Store_Supply_Order__c.object-meta.xml
<CustomObject>
    <label>Store Supply Order</label>
    <nameField>
        <label>Store Supply Order Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Store Supply Orders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Store_Supply_Order__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <description>Supplier that this order will be from</description>
    <label>Account</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Account must be a Supplier</errorMessage>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Supplier</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Store Supply Orders</relationshipLabel>
    <relationshipName>Store_Supply_Orders</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Store_Supply_Order__c/fields/Order_Amount__c.field-meta.xml
<CustomField>
    <fullName>Order_Amount__c</fullName>
    <description>Total cost of the order</description>
    <label>Order Amount</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Store_Supply_Order__c/fields/Store__c.field-meta.xml
<CustomField>
    <fullName>Store__c</fullName>
    <description>The store that is placing the order</description>
    <label>Store</label>
    <referenceTo>Store__c</referenceTo>
    <relationshipLabel>Store Supply Orders</relationshipLabel>
    <relationshipName>Store_Supply_Orders</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Store_Supply_Order__c/fields/Supplier__c.field-meta.xml
<CustomField>
    <fullName>Supplier__c</fullName>
    <description>Supplier that this order will be from</description>
    <label>Supplier</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Account must be a Supplier</errorMessage>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Supplier</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Store Supply Orders</relationshipLabel>
    <relationshipName>Store_Supply_Orders</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/Queries.cls
/**
 * @description - Class used for SOQL and SOSL examples
 */
public with sharing class Queries {
    /**
     * @description - Method with basic SOQL query examples
     */
    public static void basicSOQL() {
        // Basic query for Accounts
        List<Account> accounts = [SELECT Name 
                                FROM Account];
        for(Account acct : accounts) {
            System.debug('Acct is ' + acct);
        }

        // Only query the first 5 Accounts alphabetically
        List<Account> firstFive = [SELECT Name 
                                FROM Account 
                                ORDER BY Name ASC 
                                LIMIT 5];
        for(Account acct : firstFive) {
            System.debug('Acct in firstFive is ' + acct);
        }

        // Query all stores with a health score above 97 and order them by score, then name
        List<Store__c> stores = [SELECT Name, Latest_Health_Score__c
                                FROM Store__c
                                WHERE Latest_Health_Score__c > 97
                                ORDER BY Latest_Health_Score__c DESC, Name ASC];
        for(Store__c store : stores) {
            System.debug('Store is ' + store);
        }
    }

    /**
     * @description - Method with parent child relationship queries
     * Queries both up and down in the object hierarchy
     */
    public static void relationshipSOQL() {
        // Query parent Store record info from the child Store Supply Orders
        List<Store_Supply_Order__c> ordersWithStores = [SELECT Name, Order_Amount__c, Store__r.Name 
                                                    FROM Store_Supply_Order__c];
        for(Store_Supply_Order__c order : ordersWithStores) {
            System.debug('Order in ordersWithStores is ' + order);
        }

        // Query child Store Supply Orders from the parent Stores, note the relationship name
        List<Store__c> storesWithOrders = [SELECT Name, 
                                            (SELECT Name, Order_Amount__c 
                                            FROM Store_Supply_Orders__r) 
                                        FROM Store__c];
        for(Store__c store : storesWithOrders) {
            System.debug('Store is ' + store);
            for(Store_Supply_Order__c order : store.Store_Supply_Orders__r) {
                System.debug('Order is ' + order);
            }
        }
    }

    /**
     * @description - Dynamic SOQL examples that takes parameters to construct a SOQL query
     * @param objectName Name of the object to query
     * @param threshold Threshold to apply to the where clause
     * @param recordLimit Limit of how many records to query
     */
    public static void dynamicSOQL(String objectName, Decimal threshold, Integer recordLimit){
        // Populate the fields and object name
        String soqlQuery = 'SELECT Name FROM ' + objectName;
        // Create an empty where clause
        String whereClause = '';
        // Use a different condition per object
        if(objectName == 'Store__c') {
            whereClause += ' WHERE Latest_Health_Score__c > ' + threshold;
        } else if(objectName == 'Store_Supply_Order__c') {
            whereClause += ' WHERE Order_Amount__c > ' + threshold;
        }
        // Add the where clause to the query
        soqlQuery += whereClause;
        // Add a limit if there is one
        if(recordLimit != null) {
            soqlQuery += ' LIMIT ' + recordLimit;
        }
        // Print out the query as a sanity check
        System.debug('SOQL query is ' + soqlQuery);
        // Run the query
        List<sObject> records = Database.query(soqlQuery);
        for(sObject record : records) {
            System.debug('Record is ' + record);
        }
    }

    /**
     * @description - Method with basic SOSL query example
     */
    public static void SOSL() {
        List<List<sObject>> hubRecords = [FIND 'Hub' 
                                        IN ALL FIELDS 
                                        RETURNING Store__c(Name), Store_Supply_Order__c(Name)];
        for(List<sObject> records : hubRecords) {
            System.debug('Total records in object ' + records.size());
            for(sObject record : records) {
                System.debug('Record is ' + record);
            }
        }
    }
}