force-app/main/default/objects/Store__c/Store__c.object-meta.xml
<CustomObject>
    <description>Represents a Wired Brain Coffee Retail Store</description>
    <label>Store</label>
    <nameField>
        <label>Store Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stores</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Store_Supply_Order__c/Store_Supply_Order__c.object-meta.xml
<CustomObject>
    <label>Store Supply Order</label>
    <nameField>
        <label>Store Supply Order Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Store Supply Orders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Store_Supply_Order__c/fields/Store__c.field-meta.xml
<CustomField>
    <fullName>Store__c</fullName>
    <description>The store that is placing the order</description>
    <label>Store</label>
    <referenceTo>Store__c</referenceTo>
    <relationshipLabel>Store Supply Orders</relationshipLabel>
    <relationshipName>Store_Supply_Orders</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/BasicsTest.cls
/**
 * @description - Test class to run through basic apex classes for coverage
 */
@isTest
public with sharing class BasicsTest {
    @isTest static void testVariables() {
        Variables.primitiveVariables();
        Variables.sObjectVariables();
        Variables.collectionVariables();
        Variables.variablesWithConstants();
    }

    @isTest static void testConditionals() {
        Conditionals.ifStatements();
        Conditionals.ifElseStatements();
        Conditionals.switchStatements();
    }

    @isTest static void testLoops() {
        Loops.forLoopsBasics();
        Loops.soqlForLoops();
        Loops.whileLoops();
    }

    @isTest static void testQueries() {
        Queries.basicSOQL();
        Queries.relationshipSOQL();
        Queries.dynamicSOQL('Store__c', 97, 10);
        Queries.dynamicSOQL('Store_Supply_Order__c', 100, null);
        Queries.SOSL();
    }
}