force-app/main/default/objects/Account/fields/Primary_Contact_Email__c.field-meta.xml
<CustomField>
    <fullName>Primary_Contact_Email__c</fullName>
    <description>The primary contact email for this account</description>
    <label>Primary Contact Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Supplier.recordType-meta.xml
<RecordType>
    <fullName>Supplier</fullName>
    <active>true</active>
    <description>Record Type for Accounts to buy from</description>
    <label>Supplier</label>
</RecordType>

force-app/main/default/objects/Store__c/Store__c.object-meta.xml
<CustomObject>
    <description>Represents a Wired Brain Coffee Retail Store</description>
    <label>Store</label>
    <nameField>
        <label>Store Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stores</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Store_Supply_Order__c/Store_Supply_Order__c.object-meta.xml
<CustomObject>
    <label>Store Supply Order</label>
    <nameField>
        <label>Store Supply Order Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Store Supply Orders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Store_Supply_Order__c/fields/Order_Amount__c.field-meta.xml
<CustomField>
    <fullName>Order_Amount__c</fullName>
    <description>Total cost of the order</description>
    <label>Order Amount</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Store_Supply_Order__c/fields/Store__c.field-meta.xml
<CustomField>
    <fullName>Store__c</fullName>
    <description>The store that is placing the order</description>
    <label>Store</label>
    <referenceTo>Store__c</referenceTo>
    <relationshipLabel>Store Supply Orders</relationshipLabel>
    <relationshipName>Store_Supply_Orders</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Store_Supply_Order__c/fields/Supplier__c.field-meta.xml
<CustomField>
    <fullName>Supplier__c</fullName>
    <description>Supplier that this order will be from</description>
    <label>Supplier</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Account must be a Supplier</errorMessage>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Supplier</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Store Supply Orders</relationshipLabel>
    <relationshipName>Store_Supply_Orders</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/StoreSupplyOrderTests.cls
@isTest
public with sharing class StoreSupplyOrderTests {
    @testSetup
    static void createData(){
        Account supplier = new Account();
        supplier.Name = 'Awesome Supplier';
        supplier.Primary_Contact_Email__c = 'adam@adamtoarchitect.com';
        supplier.RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName()
                                                        .get('Supplier').getRecordTypeId();
        insert supplier;

        Store__c store = new Store__c();
        store.Name = 'Awesome Store';
        insert store;
    }

    @isTest
    static void testStoreSupplyOrderEmailFromFlow() {
        List<Store__c> stores = [SELECT ID FROM Store__c LIMIT 1];
        List<Account> suppliers = [SELECT ID FROM Account LIMIT 1];
        Store_Supply_Order__c order = new Store_Supply_Order__c();
        order.Store__c = stores[0].Id;
        order.Supplier__c = suppliers[0].Id;
        order.Order_Amount__c = 10000;
        insert order;

        Assert.isTrue(StoreSupplyOrderTriggerHandler.flowVariableMap.keySet().contains('SupplierList'),
                    'The flow variable map should contain the supplier list variable');
        Test.startTest();
        List<Account> suppliersInFlow =
                    (List<Account>)StoreSupplyOrderTriggerHandler.flowVariableMap.get('SupplierList');
        Test.stopTest();
        Assert.areEqual(suppliers[0].Id, suppliersInFlow[0].Id,
                    'The supplier sent to the flow should match the supplier on the order');
    }

    @isTest
    static void testStoreSupplyOrderController() {
        List<Store__c> stores = [SELECT ID FROM Store__c
                                WHERE Name = 'Awesome Store'];
        Id storeId = stores[0].Id;
        List<Account> suppliers = [SELECT ID FROM Account LIMIT 1];

        List<Store_Supply_Order__c> newOrders = new List<Store_Supply_Order__c>();
        for(Integer i = 0; i < 5; i++) {
            Store_Supply_Order__c order = new Store_Supply_Order__c();
            order.Store__c = storeId;
            order.Supplier__c = suppliers[0].Id;
            order.Order_Amount__c = 10000 * i;
            newOrders.add(order);
        }
        insert newOrders;

        List<Store_Supply_Order__c> ordersOnStore = [SELECT Id
                                                    FROM Store_Supply_Order__c
                                                    WHERE Store__c = :storeId];
        Assert.isTrue(ordersOnStore.size() > 0, 'There should be some store supply orders');
        Test.startTest();
        List<Store_Supply_Order__c> ordersFromController = StoreSupplyOrderController.getStoreSupplyOrders(storeId);
        Test.stopTest();
        Assert.areEqual(ordersOnStore.size(), ordersFromController.size(),
                    'The controller should get the right number of orders');
    }
}