force-app/main/default/objects/Account/fields/Primary_Contact_Email__c.field-meta.xml
<CustomField>
    <fullName>Primary_Contact_Email__c</fullName>
    <description>The primary contact email for this account</description>
    <label>Primary Contact Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Supplier.recordType-meta.xml
<RecordType>
    <fullName>Supplier</fullName>
    <active>true</active>
    <description>Record Type for Accounts to buy from</description>
    <label>Supplier</label>
</RecordType>

force-app/main/default/objects/Store_Supply_Order__c/Store_Supply_Order__c.object-meta.xml
<CustomObject>
    <label>Store Supply Order</label>
    <nameField>
        <label>Store Supply Order Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Store Supply Orders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Store_Supply_Order__c/fields/Supplier__c.field-meta.xml
<CustomField>
    <fullName>Supplier__c</fullName>
    <description>Supplier that this order will be from</description>
    <label>Supplier</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Account must be a Supplier</errorMessage>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Supplier</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Store Supply Orders</relationshipLabel>
    <relationshipName>Store_Supply_Orders</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/StoreSupplyOrderTriggerHandler.cls
/**
 * @description - Class to handle logic for trigger on Store Supply Order object
 */
public with sharing class StoreSupplyOrderTriggerHandler {
    @TestVisible
    private static Map<String, Object> flowVariableMap = new Map<String, Object>();

    /**
     * @description - Finds suppliers on new orders and sends them an email
     * @param newOrders List of newly created store supply order records
     */
    public static void handleAfterInsert(List<Store_Supply_Order__c> newOrders) {
        Set<Id> supplierIds = new Set<Id>();
        for(Store_Supply_Order__c order : newOrders){
            supplierIds.add(order.Supplier__c);
        }
        // Get the suppliers of these orders
        List<Account> suppliers = [SELECT Name, Primary_Contact_Email__c 
                                FROM Account 
                                WHERE Id IN :supplierIds];
        sendEmails(suppliers);
    }

    /**
     * @description - Calls a flow to email the suppliers
     * @param suppliers List of supplier accounts to email
     */
    private static void sendEmails(List<Account> suppliers) {
        // Populate a map referencing an input variable in the flow
        flowVariableMap.put('SupplierList', suppliers);
        // Call the flow
        Flow.Interview.New_Order_Email_to_Supplier sendEmailFlow = 
                                                        new Flow.Interview.New_Order_Email_to_Supplier(flowVariableMap);
        sendEmailFlow.start();
    }
}