force-app/main/default/objects/Account/fields/Quality_Rating__c.field-meta.xml
<CustomField>
    <fullName>Quality_Rating__c</fullName>
    <description>Score out of 100 based on quality assessment</description>
    <label>Quality Rating</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/Service_Level_Agreement__c.field-meta.xml
<CustomField>
    <fullName>Service_Level_Agreement__c</fullName>
    <label>Service Level Agreement</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Platinum Plus</fullName>
            </value>
            <value>
                <fullName>Platinum</fullName>
            </value>
            <value>
                <fullName>Gold</fullName>
            </value>
            <value>
                <fullName>Silver</fullName>
            </value>
            <value>
                <fullName>Bronze</fullName>
            </value>
            <value>
                <fullName>Blue</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/AccountTests.cls
@isTest
public with sharing class AccountTests {
    @isTest
    static void testPlatinumAccount() {
        Account acct = new Account(Name='Test Account', Quality_Rating__c=100);
        insert acct;

        Account acctAfterInsert = [SELECT Service_Level_Agreement__c FROM Account WHERE Id = :acct.Id];
        System.assertEquals('Platinum', acctAfterInsert.Service_Level_Agreement__c, 'The SLA should be Platinum');
    
        update acctAfterInsert;
    }

    @isTest
    static void testGoldAccount() {
        Account acct = new Account(Name='Test Account', Quality_Rating__c=81);
        insert acct;

        Account acctAfterInsert = [SELECT Service_Level_Agreement__c FROM Account WHERE Id = :acct.Id];
        System.assertEquals('Gold', acctAfterInsert.Service_Level_Agreement__c, 'The SLA should be Gold');
    }

    @isTest
    static void testSilverAccount() {
        Account acct = new Account(Name='Test Account', Quality_Rating__c=51);
        insert acct;

        Account acctAfterInsert = [SELECT Service_Level_Agreement__c FROM Account WHERE Id = :acct.Id];
        System.assertEquals('Silver', acctAfterInsert.Service_Level_Agreement__c, 'The SLA should be Silver');
    }

    @isTest
    static void testBronzeAccount() {
        Account acct = new Account(Name='Test Account', Quality_Rating__c=31);
        insert acct;

        Account acctAfterInsert = [SELECT Service_Level_Agreement__c FROM Account WHERE Id = :acct.Id];
        System.assertEquals('Bronze', acctAfterInsert.Service_Level_Agreement__c, 'The SLA should be Bronze');
    }
}